language: minimal

before_script:
    - |
        curl -s -L https://github.com/getzola/zola/releases/download/v0.10.1/zola-v0.10.1-x86_64-unknown-linux-gnu.tar.gz |\
        sudo tar xvzf - -C /usr/local/bin

script:
    - zola build

deploy:
    provider: pages
    skip_cleanup: true
    keep_history: true
    github_token: $GITHUB_TOKEN
    local_dir: public
    target_branch: master
    on:
        branch: code
